# Generated by Django 4.1.7 on 2023-04-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_items', models.CharField(max_length=5000)),
                ('amount', models.CharField(max_length=90)),
                ('name', models.CharField(max_length=90)),
                ('delivery_email', models.CharField(max_length=90)),
                ('user_email', models.CharField(blank=True, default=False, max_length=90, null=True)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('signature_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('oid', models.CharField(blank=True, max_length=150)),
                ('amount_paid', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(default='', max_length=100)),
                ('delievery_description', models.CharField(default=False, max_length=5000)),
                ('isdelivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('deals', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
